name: learn-git-actions
on: [push]
jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python
        with:
          python-version: '3.7'
      - run: python -v
